// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJNMaGcmhjuqsyXDpsXtLj4YSvMr8jkI',
    appId: '1:603067936438:web:2d6b41a3c67c155651c017',
    messagingSenderId: '603067936438',
    projectId: 'odqna-ai-seminar',
    authDomain: 'odqna-ai-seminar.firebaseapp.com',
    storageBucket: 'odqna-ai-seminar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytznMTfW7u99AuEQRbdiqmfaCAoMh0Bc',
    appId: '1:7413174684:android:f4ed287d5da149fce5f859',
    messagingSenderId: '7413174684',
    projectId: 'dic-caa-ra1',
    storageBucket: 'dic-caa-ra1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5RZFwdDakT3zrJ7-DMum0IHCSfyLqtBQ',
    appId: '1:7413174684:ios:9a2317f461e3a05ce5f859',
    messagingSenderId: '7413174684',
    projectId: 'dic-caa-ra1',
    storageBucket: 'dic-caa-ra1.appspot.com',
    iosBundleId: 'com.pilotcap.ttmd',
  );
}